create table netology.CUSTOMERS
(
    id int generated by default as identity primary key,
    name varchar not null,
    surname varchar not null,
    age int     not null,
    phone_number varchar not null
);

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('TIMUR', 'DUSHANOV', 31, '+77077777777');

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('ANAR', 'GAFAROV', 31, '+71011111111');

insert into netology.CUSTOMERS (name, surname, age, phone_number)
values ('ALEXEY', 'POPOVICH', 25, '+77777777777');